# Generated by Django 6.0.2 on 2026-07-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_tokenexpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='frecuencia_pago',
            field=models.CharField(choices=[('MENSUAL', 'Cada mes'), ('BIMESTRAL', 'Cada 2 meses')], db_index=True, default='MENSUAL', max_length=10),
        ),
    ]
