# Generated by Django 6.0.2 on 2026-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_sectorhealtview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorHealtModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=16, null=True)),
                ('numeroAntenas', models.IntegerField(blank=True, max_length=3, null=True)),
                ('ccqMin', models.CharField(blank=True, max_length=4, null=True)),
                ('nombreSector', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SectorHealtView',
        ),
    ]
