# Generated by Django 6.0.2 on 2026-07-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_sectorhealtmodel_delete_sectorhealtview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorhealtmodel',
            name='numeroAntenas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
