# Generated by Django 6.0.2 on 2026-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0006_alter_sectorhealtmodel_numeroantenas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorhealtmodel',
            name='ping',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
