# Generated by Django 6.0.2 on 2026-08-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0007_sectorhealtmodel_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorhealtmodel',
            name='RxTxtMin',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sectorhealtmodel',
            name='TxtMin',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='sectorhealtmodel',
            name='ccqTxtMin',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
