# Generated by Django 6.0.2 on 2026-08-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0008_sectorhealtmodel_rxtxtmin_sectorhealtmodel_txtmin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectorhealtmodel',
            old_name='RxTxtMin',
            new_name='RxtMin',
        ),
        migrations.RenameField(
            model_name='sectorhealtmodel',
            old_name='ccqTxtMin',
            new_name='ccqAntMin',
        ),
    ]
